{% set name = "fastdiff" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4dfa09c47832a8c040acda3f1f55fc0ab4d666f0e14e6951e6da78d59acd945a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest <4
    - pytest-benchmark
    - pytest-cov
  imports:
    - fastdiff
  commands:
    - pytest --cov fastdiff -vv -k "not native"

about:
  home: https://github.com/syrusakbary/fastdiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fast native implementation of diff algorithm with a pure Python fallback
  description: |
    fastdiff is a re-implementation of difflib in pure Rust compiled to
    WebAssembly to speedup different language integrations:

extra:
  recipe-maintainers:
    - bollwyvl
