travis:
  secure:
    BINSTAR_TOKEN: kDkJ7zKCcbetFcKmzgKrmo0IwkAIyitS3/LHTr9uas9tTCuTq+wWZvoHT5Z4a9iY9wIfbtbbJlSnthlSjDwiy2vndwqCBV2kWSoIwXqR/hiMRwTcgqzqmyivdaIGLTU/UlcST2de+GyWFf+lk+P5qQmiIsmrumRa32mqiOZ8QS1WMlXJXznZ/ccae09jTYvjjgRhEBuEKwyc7b4KiKLWBB7hlrGOUeSPY65Qe/OWJbBTo5eXA6sBzQSE0s13U4Z353zVt02zCuWwwSM1dUNGQuN0DIpQ3vCV6IR/ODGdDYXMLraFbWY4AAZJFpoMze+KbFlOHUa+jj/CP8coDepu7Vs4ZG0i5QzL+wfU4jMgJO0dl5v+cRF5rGyZUiE/KgyuKSq0p6avm423SCYmQP5bmxz0iVb3AOFasCPLBg0IH4J1jWm/y0cjUS+Cc1uFXTSFO8YteWRMKUDAIzkisvF4jU8F2q1PLBdkqhBJctDl7GRI57+Ky+1S4YUlKH1kjOTQ6kQp3cKKaukzMn+YUx70VDrkWDFMVtpTr0a9AVImsXKqsnHEY7MiEFMe0ZIbh1Ss9K16xbKVCIn6qxrBUV1WF0gFi4VBzOl0/AzByVLX+F6VqtdQ14SyphYhZXyO4SznaybNLo+XYtDBN7hAQA5lkRAlM9ZV4LVeOz9JElDyAOc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
